In [2]:
import pandas as pd 
import requests 
from pprint import pprint
from config import api_key
import json

## Covid CSV Data Import

In [3]:
file = r"Resources\us_counties_covid19_daily.csv"
covid_counties = pd.read_csv(file)
covid_counties.head()

         date     county       state     fips  cases  deaths
0  2020-01-21  Snohomish  Washington  53061.0      1     0.0
1  2020-01-22  Snohomish  Washington  53061.0      1     0.0
2  2020-01-23  Snohomish  Washington  53061.0      1     0.0
3  2020-01-24       Cook    Illinois  17031.0      1     0.0
4  2020-01-24  Snohomish  Washington  53061.0      1     0.0

In [4]:
covid_counties.dropna(how="any")

              date      county       state     fips  cases  deaths
0       2020-01-21   Snohomish  Washington  53061.0      1     0.0
1       2020-01-22   Snohomish  Washington  53061.0      1     0.0
2       2020-01-23   Snohomish  Washington  53061.0      1     0.0
3       2020-01-24        Cook    Illinois  17031.0      1     0.0
4       2020-01-24   Snohomish  Washington  53061.0      1     0.0
...            ...         ...         ...      ...    ...     ...
800432  2020-12-05  Sweetwater     Wyoming  56037.0   2098    10.0
800433  2020-12-05       Teton     Wyoming  56039.0   1739     2.0
800434  2020-12-05       Uinta     Wyoming  56041.0   1187     5.0
800435  2020-12-05    Washakie     Wyoming  56043.0    519     8.0
800436  2020-12-05      Weston     Wyoming  56045.0    419     2.0

[776113 rows x 6 columns]

In [5]:
covid_counties.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800437 entries, 0 to 800436
Data columns (total 6 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   date    800437 non-null  object
 1   county  800437 non-null  object
 2   state   800437 non-null  object
 3   fips    792846 non-null  float64
 4   cases   800437 non-null  int64
 5   deaths  783704 non-null  float64
dtypes: float64(2), int64(1), object(3)
memory usage: 36.6+ MB

## Transmission Level JSON Import

In [8]:
json_file = r"Resources\counties.timeseries.json"
covid_json = pd.read_json(json_file)
covid_json.head()

,fips,country,state,county,level,lat,locationId,long,population,metrics,riskLevels,cdcTransmissionLevel,actuals,annotations,lastUpdatedDate,url
0,2013,US,AK,Aleutians East Borough,county,NaN,iso1:us#iso2:us-ak#fips:02013,NaN,3337,"{'testPositivityRatio': None, 'testPositivityR...","{'overall': 2, 'testPositivityRatio': 4, 'case...",2,"{'cases': 433, 'deaths': 3, 'positiveTests': N...","{'cases': {'sources': [{'type': 'NYTimes', 'ur...",2021-10-19,https://covidactnow.org/us/alaska-ak/county/al...
1,2016,US,AK,Aleutians West Census Area,county,NaN,iso1:us#iso2:us-ak#fips:02016,NaN,5634,"{'testPositivityRatio': 0.05, 'testPositivityR...","{'overall': 2, 'testPositivityRatio': 1, 'case...",2,"{'cases': 919, 'deaths': 0, 'positiveTests': N...","{'cases': {'sources': [{'type': 'NYTimes', 'ur...",2021-10-19,https://covidactnow.org/us/alaska-ak/county/al...
2,2020,US,AK,Anchorage Municipality,county,NaN,iso1:us#iso2:us-ak#fips:02020,NaN,288000,"{'testPositivityRatio': 0.111, 'testPositivity...","{'overall': 5, 'testPositivityRatio': 2, 'case...",3,"{'cases': 52685, 'deaths': 294, 'positiveTests...","{'cases': {'sources': [{'type': 'NYTimes', 'ur...",2021-10-19,https://covidactnow.org/us/alaska-ak/county/an...
3,2050,US,AK,Bethel Census Area,county,NaN,iso1:us#iso2:us-ak#fips:02050,NaN,18386,"{'testPositivityRatio': None, 'testPositivityR...","{'overall': 5, 'testPositivityRatio': 4, 'case...",3,"{'cases': 5628, 'deaths': 25, 'positiveTests':...","{'cases': {'sources': [{'type': 'NYTimes', 'ur...",2021-10-19,https://covidactnow.org/us/alaska-ak/county/be...
4,2060,US,AK,Bristol Bay Borough,county,NaN,iso1:us#iso2:us-ak#fips:02060,NaN,836,"{'testPositivityRatio': None, 'testPositivityR...","{'overall': 0, 'testPositivityRatio': 4, 'case...",0,"{'cases': 608, 'deaths': 2, 'positiveTests': N...","{'cases': {'sources': [{'type': 'USAFacts', 'u...",2021-10-19,https://covidactnow.org/us/alaska-ak/county/br...